"""empty message

Revision ID: 0d01ef8a5d9a
Revises: 44a99d882902
Create Date: 2016-02-18 23:16:56.866483

"""

# revision identifiers, used by Alembic.
revision = '0d01ef8a5d9a'
down_revision = '44a99d882902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
